services:
  db:
    image: postgres:15-alpine
    container_name: degerinde_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=degerinde_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: degerinde_api
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: degerinde_frontend
    restart: always
    depends_on:
      - web

  nginx:
    image: nginx:alpine
    container_name: degerinde_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_degerinde.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - web

  certbot:
    image: certbot/certbot
    container_name: degerinde_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
