version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: car_price_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: car_price_api
    restart: always
    environment:
      DB_URL: postgresql+psycopg2://postgres:sifre123@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: car_price_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data:
