server {
    listen 80;
    server_name degerinde.com www.degerinde.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # location / {
    #     return 301 https://$host$request_uri;
    # }
# }

# server {
    # listen 443 ssl;
    # server_name degerinde.com www.degerinde.com;

    # ssl_certificate /etc/letsencrypt/live/degerinde.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/degerinde.com/privkey.pem;

    # Frontend Yönlendirmesi
    location / {
        # Docker internal DNS resolver
        resolver 127.0.0.11 valid=5s;
        set $frontend_upstream http://frontend:3000;
        
        proxy_pass $frontend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Yönlendirmesi
    location /api/ {
        # Docker internal DNS resolver
        resolver 127.0.0.11 valid=5s;
        set $api_upstream http://web:8000;
        
        proxy_pass $api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Long timeout for model loading / initial requests
        proxy_read_timeout 120s;
        proxy_connect_timeout 120s;
    }
}
